defaults:
  - experiment: default
  - _self_

hydra:
  run:
    dir: results/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
